#!/usr/bin/env python3
"""Compile tables and exercise candidates with the same librime release as the Android plugin."""
from pathlib import Path
import argparse, hashlib, json, os, shutil, subprocess, tarfile, time, urllib.request
parser=argparse.ArgumentParser()
parser.add_argument('--root',type=Path,default=Path.cwd())
parser.add_argument('--work',type=Path,required=True)
args=parser.parse_args(); work=args.work.resolve(); work.mkdir(parents=True,exist_ok=True)
sources=[
 ('librime','https://codeload.github.com/rime/librime/tar.gz/refs/tags/1.12.0','e3efe05603e9ec6db058bbff478540c28482513c24662e0aa336d2da72cceee4',work/'librime'),
 ('librime-lua','https://codeload.github.com/hchunhui/librime-lua/tar.gz/68f9c36','5a5012da02919c78c78f9cedbb5de1ad7b92c92eb2a65be1d1dbe38bd2af73d4',work/'librime/plugins/lua'),
 ('librime-octagram','https://codeload.github.com/lotem/librime-octagram/tar.gz/dfcc151','27f59e184661408b9c689a8c6840452304695251180907570bfb90baab59c81d',work/'librime/plugins/octagram')]
for name,url,digest,dest in sources:
 archive=work/(name+'.tar.gz')
 if not archive.exists(): archive.write_bytes(urllib.request.urlopen(url,timeout=120).read())
 assert hashlib.sha256(archive.read_bytes()).hexdigest()==digest
 if not (dest/'CMakeLists.txt').exists():
  dest.mkdir(parents=True,exist_ok=True)
  with tarfile.open(archive) as tar:
   for member in tar.getmembers():
    parts=Path(member.name).parts
    if len(parts)<2:continue
    member.name=str(Path(*parts[1:]));tar.extract(member,dest,filter='data')
build=work/'build'
subprocess.run(['cmake','-S',str(work/'librime'),'-B',str(build),'-GNinja','-DBUILD_TEST=OFF','-DENABLE_TIMESTAMP=OFF','-DENABLE_EXTERNAL_PLUGINS=OFF','-DENABLE_LOGGING=OFF','-DCMAKE_BUILD_TYPE=Release'],check=True)
subprocess.run(['cmake','--build',str(build),'-j2'],check=True)
root=args.root.resolve(); native=root/'plugin/rime/src/main/cpp'; stage=native/'xuancai-rime-ice'
for name in ['punctuation.yaml','key_bindings.yaml','symbols.yaml']:
 shutil.copyfile(native/'rime-prelude'/name,stage/name)
shutil.copyfile(native/'rime-luna-pinyin/pinyin.yaml',stage/'pinyin.yaml')
shutil.copyfile(native/'rime-essay/essay.txt',stage/'essay.txt')
shutil.copyfile(native/'default.yaml',stage/'default.yaml')
user=work/'deploy-user';user.mkdir(exist_ok=True);(stage/'build').mkdir(exist_ok=True)
started=time.monotonic()
subprocess.run([str(build/'bin/rime_deployer'),'--build',str(user),str(stage),str(stage/'build')],check=True)
smoke=work/'rime-smoke'
subprocess.run(['gcc',str(Path(__file__).parent/'check-xuancai-rime-v08.c'),'-I'+str(work/'librime/src'),'-L'+str(build/'lib'),'-Wl,-rpath,'+str(build/'lib'),'-lrime','-o',str(smoke)],check=True)
cold=work/'cold-user';cold.mkdir(exist_ok=True)
result=subprocess.run([str(smoke),str(stage),str(cold),str(stage/'build')],check=True,text=True,stdout=subprocess.PIPE)
print(result.stdout)
checks=work/'checks';checks.mkdir(exist_ok=True);(checks/'native-candidates.txt').write_text(result.stdout)
# Exercise the same dedicated config file generated by the Android fuzzy-settings UI.
fuzzy=work/'fuzzy-user';fuzzy.mkdir(exist_ok=True)
rules=['derive/^n/l/','derive/^l/n/','derive/^([zcs])h/$1/','derive/^([zcs])([^h])/$1h$2/','derive/ang$/an/','derive/an$/ang/']
(fuzzy/'xuancai_mobile.yaml').write_text('patch:\n  speller/algebra/+:\n'+''.join("    - '"+r+"'\n" for r in rules))
(fuzzy/'build').mkdir(exist_ok=True)
subprocess.run([str(build/'bin/rime_deployer'),'--build',str(fuzzy),str(stage),str(fuzzy/'build')],check=True)
import yaml
compiled=yaml.safe_load((fuzzy/'build/rime_ice.schema.yaml').read_text())
assert all(rule in compiled['speller']['algebra'] for rule in rules), 'User fuzzy patch was not deployed'
normal=yaml.safe_load((stage/'build/rime_ice.schema.yaml').read_text())
assert all(rule not in normal['speller']['algebra'] for rule in rules), 'Fuzzy must default to off'
assert normal['grammar']['language']=='zh-hans-t-essay-bgw-compact'
assert normal['xuancai_correction']['enable_correction'] is True
assert normal['translator']['enable_correction'] is False
assert 'lua_translator@*xuancai_correction' in normal['engine']['translators']
manifest={'engine':'1.12.0','plugins':{'lua':'68f9c36','octagram':'dfcc151'},'sources':{name:{'url':url,'sha256':digest} for name,url,digest,_ in sources},'files_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted((stage/'build').iterdir()) if p.is_file() and p.name != 'PREBUILT.json'}}
(stage/'build/PREBUILT.json').write_text(json.dumps(manifest,indent=2)+'\n')
(checks/'prebuilt.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Full native checks passed; precompiled data preparation took %.1fs'%(time.monotonic()-started))
