#!/usr/bin/env python3
"""Compile tables and exercise candidates with the same librime release as the Android plugin."""
from pathlib import Path
import argparse, hashlib, json, os, shutil, subprocess, sys, tarfile, time, urllib.request
parser=argparse.ArgumentParser()
parser.add_argument('--root',type=Path,default=Path.cwd())
parser.add_argument('--work',type=Path,required=True)
args=parser.parse_args(); work=args.work.resolve(); work.mkdir(parents=True,exist_ok=True)
sources=[
 ('librime','https://codeload.github.com/rime/librime/tar.gz/refs/tags/1.12.0','e3efe05603e9ec6db058bbff478540c28482513c24662e0aa336d2da72cceee4',work/'librime'),
 ('librime-lua','https://codeload.github.com/hchunhui/librime-lua/tar.gz/68f9c36','5a5012da02919c78c78f9cedbb5de1ad7b92c92eb2a65be1d1dbe38bd2af73d4',work/'librime/plugins/lua'),
 ('librime-octagram','https://codeload.github.com/lotem/librime-octagram/tar.gz/dfcc151','27f59e184661408b9c689a8c6840452304695251180907570bfb90baab59c81d',work/'librime/plugins/octagram')]
for name,url,digest,dest in sources:
 archive=work/(name+'.tar.gz')
 if not archive.exists(): archive.write_bytes(urllib.request.urlopen(url,timeout=120).read())
 assert hashlib.sha256(archive.read_bytes()).hexdigest()==digest
 if not (dest/'CMakeLists.txt').exists():
  dest.mkdir(parents=True,exist_ok=True)
  with tarfile.open(archive) as tar:
   for member in tar.getmembers():
    parts=Path(member.name).parts
    if len(parts)<2:continue
    member.name=str(Path(*parts[1:]));tar.extract(member,dest,filter='data')
build=work/'build'
subprocess.run(['cmake','-S',str(work/'librime'),'-B',str(build),'-GNinja','-DBUILD_TEST=OFF','-DENABLE_TIMESTAMP=OFF','-DENABLE_EXTERNAL_PLUGINS=OFF','-DENABLE_LOGGING=OFF','-DCMAKE_BUILD_TYPE=Release'],check=True)
subprocess.run(['cmake','--build',str(build),'-j2'],check=True)
root=args.root.resolve(); native=root/'plugin/rime/src/main/cpp'; stage=native/'xuancai-rime-ice'
for name in ['punctuation.yaml','key_bindings.yaml','symbols.yaml']:
 shutil.copyfile(native/'rime-prelude'/name,stage/name)
shutil.copyfile(native/'rime-luna-pinyin/pinyin.yaml',stage/'pinyin.yaml')
shutil.copyfile(native/'rime-essay/essay.txt',stage/'essay.txt')
shutil.copyfile(native/'default.yaml',stage/'default.yaml')
user=work/'deploy-user';user.mkdir(exist_ok=True);(stage/'build').mkdir(exist_ok=True)
started=time.monotonic()
subprocess.run([str(build/'bin/rime_deployer'),'--build',str(user),str(stage),str(stage/'build')],check=True)
smoke=work/'rime-smoke'
subprocess.run(['gcc',str(Path(__file__).parent/'check-xuancai-rime-v08.c'),'-I'+str(work/'librime/src'),'-L'+str(build/'lib'),'-Wl,-rpath,'+str(build/'lib'),'-lrime','-o',str(smoke)],check=True)
cold=work/'cold-user';cold.mkdir(exist_ok=True)
result=subprocess.run([str(smoke),str(stage),str(cold),str(stage/'build')],check=True,text=True,stdout=subprocess.PIPE)
print(result.stdout)
checks=work/'checks';checks.mkdir(exist_ok=True);(checks/'native-candidates.txt').write_text(result.stdout)
adjacent_smoke=work/'rime-adjacent-smoke'
subprocess.run(['gcc',str(Path(__file__).parent/'check-axiang-adjacent-correction.c'),'-I'+str(work/'librime/src'),'-L'+str(build/'lib'),'-Wl,-rpath,'+str(build/'lib'),'-lrime','-o',str(adjacent_smoke)],check=True)
adjacent_user=work/'adjacent-user'
if adjacent_user.exists(): shutil.rmtree(adjacent_user)
adjacent_user.mkdir()
adjacent_result=subprocess.run([str(adjacent_smoke),str(stage),str(adjacent_user),str(stage/'build')],check=True,text=True,stdout=subprocess.PIPE)
(checks/'native-adjacent-candidates.txt').write_text(adjacent_result.stdout)
print(adjacent_result.stdout)
index_result=subprocess.run([sys.executable,str(Path(__file__).parent/'check-axiang-typo-index.py'),'--stage',str(stage)],check=True,text=True,stdout=subprocess.PIPE)
(checks/'adjacent-index.json').write_text(index_result.stdout)
index_summary=json.loads(index_result.stdout)
print('Adjacent index: %s directed key pairs, %s queries; bounded cache/search checks passed.' %
      (index_summary['directed_neighbour_pairs'], index_summary['queries']))
t9_smoke=work/'rime-t9-smoke'
subprocess.run(['gcc',str(Path(__file__).parent/'check-axiang-rime-t9.c'),'-I'+str(work/'librime/src'),'-L'+str(build/'lib'),'-Wl,-rpath,'+str(build/'lib'),'-lrime','-o',str(t9_smoke)],check=True)
t9_user=work/'t9-user'
if t9_user.exists(): shutil.rmtree(t9_user)
t9_user.mkdir()
t9_result=subprocess.run([str(t9_smoke),str(stage),str(t9_user),str(stage/'build')],check=True,text=True,stdout=subprocess.PIPE)
print(t9_result.stdout)
(checks/'native-t9-candidates.txt').write_text(t9_result.stdout)
# Exercise the same dedicated config file generated by the Android fuzzy-settings UI.
fuzzy=work/'fuzzy-user';fuzzy.mkdir(exist_ok=True)
rules=['derive/^n/l/','derive/^l/n/','derive/^([zcs])h/$1/','derive/^([zcs])([^h])/$1h$2/','derive/ang$/an/','derive/an$/ang/']
(fuzzy/'xuancai_mobile.yaml').write_text('patch:\n  speller/algebra/+:\n'+''.join("    - '"+r+"'\n" for r in rules))
(fuzzy/'build').mkdir(exist_ok=True)
subprocess.run([str(build/'bin/rime_deployer'),'--build',str(fuzzy),str(stage),str(fuzzy/'build')],check=True)
import yaml
compiled=yaml.safe_load((fuzzy/'build/rime_ice.schema.yaml').read_text())
assert all(rule in compiled['speller']['algebra'] for rule in rules), 'User fuzzy patch was not deployed'
normal=yaml.safe_load((stage/'build/rime_ice.schema.yaml').read_text())
assert all(rule not in normal['speller']['algebra'] for rule in rules), 'Fuzzy must default to off'
assert normal['grammar']['language']=='zh-hans-t-essay-bgw-compact'
assert normal['xuancai_correction']['enable_correction'] is True
assert normal['translator']['enable_correction'] is False
assert normal['xuancai_exact']['spelling_hints'] == 32
assert normal['xuancai_exact']['always_show_comments'] is True
assert 'lua_translator@*xuancai_correction' in normal['engine']['translators']
assert 'script_translator@xuancai_user' in normal['engine']['translators']
assert 'xuancai_user' in normal['schema']['dependencies']
assert normal['xuancai_user']['dictionary']=='xuancai_user'
dictionary=yaml.safe_load((stage/'rime_ice.dict.yaml').read_text().split('...',1)[0])
tables=dictionary['import_tables']
assert tables.index('cn_dicts/8105') < tables.index('cn_dicts/41448')
assert 'cn_dicts/xuancai_mobile' in tables
assert (stage/'build/xuancai_user.table.bin').is_file()
t9=yaml.safe_load((stage/'build/rime_ice_t9.schema.yaml').read_text())
assert str(t9['speller']['alphabet'])=='23456789'
assert t9['translator']['dictionary']=='rime_ice'
assert t9['translator']['prism']=='rime_ice_t9'
assert t9['translator']['user_dict']=='rime_ice'
assert t9['xuancai_user']['dictionary']=='xuancai_user'
assert t9['xuancai_user']['prism']=='xuancai_user_t9'
assert t9['engine']['filters'].index('lua_filter@*t9_preedit') < t9['engine']['filters'].index('simplifier@emoji')
assert (stage/'build/rime_ice_t9.prism.bin').is_file()
assert (stage/'build/xuancai_user_t9.prism.bin').is_file()
assert not (stage/'build/rime_ice_t9.table.bin').exists(), 'T9 must reuse the full Chinese table'
assert not (stage/'build/xuancai_user_t9.table.bin').exists(), 'T9 must reuse the personal table'

# A phone import writes only the small personal dictionary and re-deploys. Check
# real candidates after both initial import and an update, and prove the large
# precompiled dictionary is neither rewritten nor copied into the user build.
personal=work/'personal-user';personal.mkdir(exist_ok=True)
header=(stage/'xuancai_user.dict.yaml').read_text()
main_table=stage/'build/rime_ice.table.bin'
main_before=(main_table.stat().st_mtime_ns,hashlib.sha256(main_table.read_bytes()).hexdigest())
personal_rows='炫彩个人词条验证\txuan cai ge ren ci tiao yan zheng\t100\n安卓离线部署词典\tan zhuo li xian bu shu ci dian\t100\n'
personal_dict=personal/'xuancai_user.dict.yaml'
personal_dict.write_text(header.replace('"2026-10-04"','"native-import-1"')+personal_rows)
(personal/'build').mkdir(exist_ok=True)
subprocess.run([str(build/'bin/rime_deployer'),'--build',str(personal),str(stage),str(personal/'build')],check=True)
personal_result=subprocess.run([str(smoke),str(stage),str(personal),str(stage/'build'),'personal'],check=True,text=True,stdout=subprocess.PIPE)
(checks/'native-personal-dictionary.txt').write_text(personal_result.stdout)
print(personal_result.stdout)
t9_personal=subprocess.run([str(t9_smoke),str(stage),str(personal),str(stage/'build'),'personal'],check=True,text=True,stdout=subprocess.PIPE)
with (checks/'native-t9-candidates.txt').open('a') as output: output.write(t9_personal.stdout)
print(t9_personal.stdout)
personal_dict.write_text(header.replace('"2026-10-04"','"native-import-2"')+personal_rows+'独立导入词条\tdu li dao ru ci tiao\t100\n')
subprocess.run([str(build/'bin/rime_deployer'),'--build',str(personal),str(stage),str(personal/'build')],check=True)
updated_result=subprocess.run([str(smoke),str(stage),str(personal),str(stage/'build'),'personal-update'],check=True,text=True,stdout=subprocess.PIPE)
with (checks/'native-personal-dictionary.txt').open('a') as output: output.write(updated_result.stdout)
print(updated_result.stdout)
t9_updated=subprocess.run([str(t9_smoke),str(stage),str(personal),str(stage/'build'),'personal-update'],check=True,text=True,stdout=subprocess.PIPE)
with (checks/'native-t9-candidates.txt').open('a') as output: output.write(t9_updated.stdout)
print(t9_updated.stdout)
assert main_before==(main_table.stat().st_mtime_ns,hashlib.sha256(main_table.read_bytes()).hexdigest()), 'Personal import changed the full dictionary'
assert not (personal/'build/rime_ice.table.bin').exists(), 'Personal import unnecessarily compiled the full dictionary'
personal_dict.write_text(header.replace('"2026-10-04"','"native-import-clear"'))
subprocess.run([str(build/'bin/rime_deployer'),'--build',str(personal),str(stage),str(personal/'build')],check=True)
assert (personal/'build/xuancai_user.table.bin').is_file(), 'Cleared personal dictionary is not deployable'
print('Personal dictionary import/update/clear use real candidates and reuse the full precompiled table.')
manifest={'engine':'1.12.0','plugins':{'lua':'68f9c36','octagram':'dfcc151'},'sources':{name:{'url':url,'sha256':digest} for name,url,digest,_ in sources},'files_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted((stage/'build').iterdir()) if p.is_file() and p.name != 'PREBUILT.json'}}
(stage/'build/PREBUILT.json').write_text(json.dumps(manifest,indent=2)+'\n')
(checks/'prebuilt.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Full native checks passed; precompiled data preparation took %.1fs'%(time.monotonic()-started))
